apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-stack
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/managed-by: Helm
    chart: kube-prometheus-stack-13.13.1
    heritage: Helm
    release: prometheus-stack
    self-monitor: "true"
  name: prometheus-stack-kube-prom-prometheus-ext
  namespace: monitoring
spec:
  clusterIP:
  clusterIPs:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    prometheus: prometheus-stack-kube-prom-prometheus
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
