apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: custom-ip-pool
      protocol: layer2
      addresses:
      - 172.28.128.5-172.28.128.200